-- Display the first 20 records from the customer table
SELECT *
FROM customer
LIMIT 20;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,
       SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,
       purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd > (
      SELECT AVG(purchase_amount_usd)
      FROM customer
  );


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(review_rating::numeric), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount_usd), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_spend,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           (SUM(CASE
               WHEN discount_applied = 'Yes' THEN 1
               ELSE 0
           END)::numeric / COUNT(*)) * 100, 2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.
SELECT customer_id,
       previous_purchases,
       CASE
           WHEN previous_purchases = 1 THEN 'New'
           WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
           ELSE 'Loyal'
       END AS customer_segment
FROM customer;


-- Count the number of customers in each segment.
SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM (
    SELECT CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
) AS segments
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH product_orders AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

-- Display only the top 3 products from each category.
SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM product_orders
WHERE item_rank <= 3;


-- Q9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
;

-- Q10. What is the revenue contribution of each age group?
SELECT age,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer
GROUP BY age
ORDER BY total_revenue DESC;